version: "3.7"

services:
  host_01:
    container_name: host01
    hostname: host01
    build: .
    command: tail -F anything
    networks:
      home_net:
        ipv4_address: 192.168.124.10

networks:
  home_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.124.0/24
